### ISSUE TITLE
Uploading a new project while selecting file fails

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#10]
Details: While uploading the project with file section it fails
Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

Admin able to successfully login
Click on Upload Tab
Fills out compulsory details
Clicks on file selection
Clicks on Upload
Throws an Error Message 

![screen shot 2019-03-02 at 1 26 44 pm](https://user-images.githubusercontent.com/35909083/53687582-7dfd9100-3cf3-11e9-8c76-74eed2e59e2d.png)

![screen shot 2019-03-02 at 1 27 17 pm](https://user-images.githubusercontent.com/35909083/53687586-82c24500-3cf3-11e9-9703-4a7140b41145.png)

**Comment by niminp** [comment]
I am not able to reproduce this bug, I created a new project with a file upload and seems to work. 

https://ec2-3-95-13-178.compute-1.amazonaws.com/project/12/

Can you try again?
