### ISSUE TITLE
Sign in is not aligned with the Title ( Login )

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#11]
Details: Sign in is not aligned with the Title 
Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

User Clicks on Sign in Tab

![screen shot 2019-03-02 at 2 00 53 pm](https://user-images.githubusercontent.com/35909083/53687611-daf94700-3cf3-11e9-8d9d-7388640b8b6d.png)

**Comment by niminp** [comment]
Looks like auto margins were added without defining width. It should now be fixed
