### ISSUE TITLE
Admin wants to add same programming lang and Frameworks. 

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#2]
Details:  Admin wants to add same programming lang and Frameworks. 
Severity of problem: Medium

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

1. Admin able to successfully login
2. Click on Upload Tab
3. Enter same Programming and Framework details
4. Fills out compulsory details 
5. Clicks on Upload 
6. Projects gets uploaded successfully. 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/35909083/53620162-2d7d1b00-3baf-11e9-8882-ff8b93223d99.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/35909083/53620167-340b9280-3baf-11e9-815d-48f04c7ff4ba.png">

**Comment by niminp** [comment]
This is now fixed, we are now ignoring case when validating duplicates.

**Comment by Hgami** [comment]
Tested the Bug. 

Even when with no duplicates, by default system is converting value into lower case which should not be the case. System should validate if the value is already present or not, and its present it should throw an error saying Values are already presented. 

A new Bug is created with more details. 

Thank you
Hardik Gami
