### ISSUE TITLE
GUI Of Project Detail page is different  for different projects 

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#3]
Details:  GUI Of Project Detail page is different  for different projects 
Severity of problem: Low

Bug Reporter: Hardik Gami

Assignee : Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

1. Admin able to successfully login
2. Click on below two  projects to see details.
               a. Project Name : First Project
               b. Project Name : Test Project

1) First Project
<img width="442" alt="image" src="https://user-images.githubusercontent.com/35909083/53620214-62896d80-3baf-11e9-9ab5-a258daae7801.png">

2) Test Project 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/35909083/53620228-6c12d580-3baf-11e9-870b-388ac0540584.png">

**Comment by niminp** [comment]
Width has been increased by Luis which fixes this issue.

**Comment by Hgami** [comment]
Tested the Bug. 

All the Description page looks same. 

Thank you
Hardik Gami
