### ISSUE TITLE
Admin cannot uncheck uploaded file in upload Pag

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#4]
Details:  Admin cannot undo the file selection in Upload page
Severity of problem: Fatal

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

1. Admin able to successfully login
2. Click on Upload Tab
3. Clicks on Choose File:  Selects file from Local Machine
4. Decides to undo the selection of file 
5. No options to undo the selection.  

<img width="442" alt="image" src="https://user-images.githubusercontent.com/35909083/53620268-949acf80-3baf-11e9-9e3e-3135de41236b.png">

Suggested fix: To have delete button along along choose file button which will allow user to remove the selection of file

**Comment by niminp** [comment]
A "clear file" button has been added to help clear the file once it has been selected.

**Comment by Hgami** [comment]
Tested the Bug Again. 

Clear Button works properly and the selected project gets clear.

Thank you
Hardik Gami
