### ISSUE TITLE
Allowing invalid links while uploading the project 

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#5]
Details: Allowing invalid links while uploading the project 
Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

Admin able to successfully login
Click on Upload Tab
Enter Enters invalid links
Fills out compulsory details
Clicks on Upload
Projects gets uploaded successfully.

Suggested fix: Validation should be in place if the link are valid or not. 

![screen shot 2019-03-02 at 1 29 36 pm](https://user-images.githubusercontent.com/35909083/53687246-99669d00-3cef-11e9-9d21-c9f9f3a70389.png)

**Comment by niminp** [comment]
No way to limit validate invalid links, I will ensure URL validation is added however it will not validate invalid urls, www.facebook could potentially be a valid URL as it follows the correct URL structure.  No fix necessary

**Comment by Hgami** [comment]
Can't we add regex or any other validation when user tries to upload the project ? 
For example - 

regex = re.compile(
        r'^(?:http|ftp)s?://' # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' #domain...
        r'localhost|' #localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)

print re.match(regex, "http://www.example.com")   # True
print re.match(regex, "example.com") #False

**Comment by niminp** [comment]
I have seen this regex before, the additional validation I added will add all of these validations, however it will not be successful in validating 'http://www.example'.  Since there is a '.' present it is considered a valid URL (unless we gather all the major domain and validate, which is unnecessary and does not scale with new high level domains being added constantly).
