### ISSUE TITLE
Valid link's not opening properly 

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#6]
Details: Throwing Error message when trying to open valid link
Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

Admin able to successfully login
Click on Upload Tab
Enter Enters valid link ( www.google.com)
Fills out compulsory details
Clicks on Upload
Projects gets uploaded successfully.��

Suggested fix: Validation should be in place if the link are valid or not.

![screen shot 2019-03-02 at 1 29 36 pm](https://user-images.githubusercontent.com/35909083/53687297-3590a400-3cf0-11e9-8457-f6a64050ddb6.png)

![screen shot 2019-03-02 at 1 29 52 pm](https://user-images.githubusercontent.com/35909083/53687296-3590a400-3cf0-11e9-9028-98d6f137c2d9.png)

**Comment by niminp** [comment]
URL field validation has been added to the upload form, it will now validate URL.  Once valid url are uploaded, it will render the links correctly.
