### ISSUE TITLE
All the project description in Homepage are in Uppercase. 

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#7]
Details: In Home page, all the project description are in upper case. 
Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

Admin able to successfully login
Click on Upload Tab
Fills out compulsory details
Clicks on Upload
Projects gets uploaded successfully.
Go to Home Page. 
Description are in Upper case irrespective of whatever case it was uploaded

![screen shot 2019-03-02 at 1 28 28 pm](https://user-images.githubusercontent.com/35909083/53687337-b5b70980-3cf0-11e9-9ffa-ff86f794b367.png)

**Comment by lgimenezBU** [comment]
This is due to the font used. I can swap it.
