### ISSUE TITLE
Name of Model Title is Missing 

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#8]
Details: While deleting the project name of Model title is not present

Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug

Admin able to successfully login
Click on project description
Clicks on delete project 

Suggested fix: Name of project should be Model title 

![screen shot 2019-03-02 at 1 23 36 pm](https://user-images.githubusercontent.com/35909083/53687375-26f6bc80-3cf1-11e9-9b2c-beebc479cb44.png)

**Comment by niminp** [comment]
Modal title has been added, it should now show "Are you sure?"
