### ISSUE TITLE
Keywords, TeamMembers, Frameworks and Programming Lang all are in lowercase

### ISSUE THREAD

**Issue by Hgami** [niminp/cs633_archive#9]
Details: Keywords, TeamMembers, Frameworks and Programming Lang all are in lowercase

Severity of problem: Serious

Bug Reporter: Hardik Gami

Assignee: Development Team
Problem and how to reproduce it
Please see below steps and screenshots to reproduce the same bug
Admin able to successfully login
Click on upload project 
Fills out KeyMembers,TeamMembers, Frameworks and Programming Lang

Suggested fix: All the Values should be exactly what User input provides 

![screen shot 2019-03-02 at 1 26 28 pm](https://user-images.githubusercontent.com/35909083/53687398-67563a80-3cf1-11e9-96db-f7e4c8a0c04b.png)

**Comment by niminp** [comment]
this was intentional to ensure there is no case to these terms.  I can change this if it is now what is needed.
